### ISSUE TITLE
PrologException under high load (30 agents all making prolog queries at the same time)

### ISSUE THREAD

**Issue by ayoung012** [ssardina-agts/sarl-prolog-cap#12]
I intermittently get this error when using askOnce under high load (around 30 agents all making prolog queries at once).

It has me absolutely stumped. I don't recognise the not_a_list and is_not predicates.

```
[SEVERE, 8:04:14pm, agentA11] PrologException: error(existence_error(procedure, ':'(error, '/'(not_a_list, 2))), context(':'(error, '/'(is_not, 2)), _104))
org.jpl7.PrologException: PrologException: error(existence_error(procedure, ':'(error, '/'(not_a_list, 2))), context(':'(error, '/'(is_not, 2)), _104))
        at org.jpl7.Query.fetchNextSolution(Query.java:438)
        at org.jpl7.Query.hasMoreSolutions(Query.java:342)
        at org.jpl7.Query.oneSolution(Query.java:872)
        at org.jpl7.Query.oneSolution(Query.java:932)
        at io.sarl.extras.SWIJPL_KB_Prolog.askOnceIn(SWIJPL_KB_Prolog.java:233)
        at io.sarl.extras.SWIJPL_KB_Prolog.askOnce(SWIJPL_KB_Prolog.java:229)
        at au.edu.rmit.agtgrp.agtcity.sarl.beliefs.SWI_KB_AgtCity.kb_pickDestination(SWI_KB_AgtCity.java:99)
        at au.edu.rmit.agtgrp.agtcity.sarl.beliefs.KB_AgtCity$ContextAwareCapacityWrapper.kb_pickDestination(KB_AgtCity.java:121)
        at au.edu.rmit.agtgrp.agtcity.sarl.behaviors.NavigationRandom.$behaviorUnit$E_EntitySensed$1(NavigationRandom.java:72)
        at au.edu.rmit.agtgrp.agtcity.sarl.behaviors.NavigationRandom.lambda$$guardEvaluator$E_EntitySensed$1(NavigationRandom.java:161)
        at io.sarl.sre.skills.bic.SchedulesSkill.lambda$executeAsap$1(SchedulesSkill.java:1089)
        at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.coreRun(SchedulesSkill.java:408)
        at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.internalRun(SchedulesSkill.java:449)
        at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:111)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
When I run the same askOnce query on the kb dump, it runs fine. 

I am running Java 11, SARL 0.12 and swipl-8.2.0 on Linux.

I see some `not_a_list` in the SWI-Prolog source, so maybe an issue there?
```
./swipl/swipl-8.2.0/library/error.pl:    not_a_list(list, X).
./swipl/swipl-8.2.0/library/error.pl:    not_a_list(list(Of), X).
./swipl/swipl-8.2.0/library/error.pl:    not_a_list(list(char), X).
./swipl/swipl-8.2.0/library/error.pl:    not_a_list(list(code), X).
./swipl/swipl-8.2.0/library/error.pl:not_a_list(Type, X) :-
```

**Comment by ayoung012** [comment]
Another such Exception I hit under high load is the below:
```
[SEVERE, 8:53:29pm, agentA26] PrologException: error(existence_error(procedure, ':'(swi_option, '/'(get_option, 2))), context(':'(swi_option, '/'(option, 3)), _112))
org.jpl7.PrologException: PrologException: error(existence_error(procedure, ':'(swi_option, '/'(get_option, 2))), context(':'(swi_option, '/'(option, 3)), _112))
        at org.jpl7.Query.fetchNextSolution(Query.java:438)
        at org.jpl7.Query.hasMoreSolutions(Query.java:342)
        at org.jpl7.Query.oneSolution(Query.java:872)
        at org.jpl7.Query.hasSolution(Query.java:950)
        at org.jpl7.Query.hasSolution(Query.java:978)
        at io.sarl.extras.SWIJPL_KB_Prolog.dump_kb(SWIJPL_KB_Prolog.java:133)
        at io.sarl.extras.SWIJPL_KB_Prolog.dump_kb(SWIJPL_KB_Prolog.java:126)
        at au.edu.rmit.agtgrp.agtcity.sarl.agents.smart.SingleAgent.$behaviorUnit$E_EntitySensed$4(SingleAgent.java:338)
        at au.edu.rmit.agtgrp.agtcity.sarl.agents.smart.SingleAgent.lambda$$guardEvaluator$E_EntitySensed$11(SingleAgent.java:495)
        at io.sarl.sre.skills.bic.SchedulesSkill.lambda$executeAsap$1(SchedulesSkill.java:1089)
        at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.coreRun(SchedulesSkill.java:408)
        at io.sarl.sre.skills.bic.SchedulesSkill$TaskRunner.internalRun(SchedulesSkill.java:449)
        at io.sarl.sre.services.executor.SreRunnable.run(SreRunnable.java:111)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ayoung012** [comment]
Upgrading swipl to 8.4.1 seems to have resolved the issue. I am no longer able to reproduce these exceptions.
